name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      # Students replace these with their actual values
      DOCKER_USERNAME: "benjaminjosephj"  
      DOCKER_PAT: "dckr_pat_4IcXNRFGo6zMm4M5XzoAHSFinAY" 
      IMAGE_NAME: "benjaminjosephj/demo"
      IMAGE_TAG: "frontend"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: frontend
        run: |
          npm ci
          npm install eslint --save-dev

      #- name: Lint with ESLint
      #  working-directory: frontend
      #  run: npx eslint .

      #- name: Scan for secrets
       # uses: gitleaks/gitleaks-action@v2
        #env:
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        working-directory: frontend
        run: |
          # Build the image
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          
          # Login using PAT
          echo $DOCKER_PAT | docker login -u $DOCKER_USERNAME --password-stdin
          
          # Push the image
          docker push $IMAGE_NAME:$IMAGE_TAG
          
          # Logout for security
          docker logout

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: table
